### ISSUE TITLE
Firefox for Android

### ISSUE THREAD

**Issue by aaronholsonege** [aarongloege/pointer#1]
Simulated event are not ignore in Firefox for Android.

It seems the touch event API is different on Firefox? Looking into it.

**Comment by ZachSaucier** [comment]
Pointer events with this polyfill are currently not working for me in Firefox for Android. Is this because it is supported behind a flag in Firefox?

In order to get the test page to work I have to enable `dom.w3c_pointer_events.enabled` in its `about:config`.

Test URL: https://codepen.io/GreenSock/pen/bf3d9dfe885d2ccaece079db1efde034
